Fix errors with undeclared variables in extractkern.c
The errors from gcc:
extractkern.c: In function ‘make_kernel’:
extractkern.c:441:21: error: ‘rPixX’ undeclared (first use in this function)
extractkern.c:442:21: error: ‘rPixY’ undeclared (first use in this function)

These variables are declared in globals.h. Including the header fixes
the compiler error.