Fix error caused by implicit declaration of function gethostname()
The error produced by gcc:
main.c:251:5: error: implicit declaration of function ‘gethostname’

This is a warning on CentOS 5, but turns into an error on CentOS 6 and
higher. Adding -D_GNU_SOURCE to the compiler options defines the
gethostname() function in the unistd.h header, and fixes the problem.